# Generated by Django 5.2.7 on 2026-09-22 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PerfilOperacional",
            fields=[
                (
                    "usuario_id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("matricula", models.CharField(max_length=20, unique=True)),
                ("cargo", models.CharField(blank=True, default="", max_length=150)),
                (
                    "avatar",
                    models.CharField(default="/avatars/default.png", max_length=255),
                ),
                ("allowed_menus", models.JSONField(blank=True, default=list)),
            ],
            options={
                "verbose_name": "Perfil Operacional",
                "verbose_name_plural": "Perfis Operacionais",
                "db_table": "perfil_operacional",
            },
        ),
    ]
