# Generated by Django 5.2.7 on 2026-09-23 20:28

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
import uuid
from django.db import migrations, models


def criar_extensao_vector(apps, schema_editor):
    if schema_editor.connection.alias != "default":
        return
    schema_editor.execute("CREATE EXTENSION IF NOT EXISTS vector;")


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(criar_extensao_vector, migrations.RunPython.noop),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'idioma',
            },
        ),
        migrations.CreateModel(
            name='NivelSigilo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, unique=True)),
                ('ordinal', models.PositiveSmallIntegerField(unique=True)),
            ],
            options={
                'db_table': 'nivel_sigilo',
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, unique=True)),
            ],
            options={
                'db_table': 'tipo_documento',
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('descricao', models.CharField(blank=True, default='', max_length=500)),
                ('eh_governanca_central', models.BooleanField(default=False, help_text='Área que recebe solicitações sem responsável identificável.')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'area',
                'constraints': [models.UniqueConstraint(condition=models.Q(('eh_governanca_central', True)), fields=('eh_governanca_central',), name='uq_area_governanca_central')],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.CharField(blank=True, default='', max_length=500)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categorias', to='core_api.area')),
            ],
            options={
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=300)),
                ('identificador_codigo', models.CharField(max_length=100)),
                ('numero_revisao', models.CharField(max_length=30)),
                ('data_emissao', models.DateField()),
                ('status', models.CharField(choices=[('VIGENTE', 'Vigente'), ('SUBSTITUIDO', 'Substituído'), ('CANCELADO', 'Cancelado'), ('EM_REVISAO', 'Em revisão')], default='VIGENTE', max_length=20)),
                ('origem_fonte', models.CharField(max_length=200)),
                ('arquivo_original_url', models.CharField(max_length=500)),
                ('data_vigencia', models.DateField(blank=True, null=True)),
                ('data_validade', models.DateField(blank=True, null=True)),
                ('conteudo', models.TextField(blank=True, help_text='Texto extraído via OCR - preenchido pelo pipeline, não no upload.', null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_responsavel', to='core_api.perfiloperacional')),
                ('usuario_upload', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_upload', to='core_api.perfiloperacional')),
            ],
            options={
                'db_table': 'documento',
            },
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(help_text='Posição do chunk dentro do documento.')),
                ('pagina_inicio', models.PositiveIntegerField(blank=True, null=True)),
                ('pagina_fim', models.PositiveIntegerField(blank=True, null=True)),
                ('qualidade', models.FloatField(blank=True, null=True)),
                ('texto', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='core_api.documento')),
            ],
            options={
                'db_table': 'chunk',
                'ordering': ['documento_id', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_principal', models.BooleanField(default=False)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_api.area')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_api.documento')),
            ],
            options={
                'db_table': 'documento_area',
            },
        ),
        migrations.AddField(
            model_name='documento',
            name='areas',
            field=models.ManyToManyField(related_name='documentos', through='core_api.DocumentoArea', to='core_api.area'),
        ),
        migrations.CreateModel(
            name='EmbeddingVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=60)),
                ('dimensao', models.PositiveIntegerField(default=1024)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1024)),
                ('vigente', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='core_api.chunk')),
            ],
            options={
                'db_table': 'embedding_version',
            },
        ),
        migrations.AddField(
            model_name='documento',
            name='idioma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='core_api.idioma'),
        ),
        migrations.CreateModel(
            name='LogAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('VISUALIZACAO', 'Visualização'), ('DOWNLOAD', 'Download'), ('EXPORTACAO', 'Exportação')], max_length=20)),
                ('ip_origem', models.GenericIPAddressField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_acesso', to='core_api.documento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_acesso', to='core_api.perfiloperacional')),
            ],
            options={
                'db_table': 'log_acesso',
            },
        ),
        migrations.AddField(
            model_name='documento',
            name='nivel_sigilo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='core_api.nivelsigilo'),
        ),
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.CharField(blank=True, default='', max_length=500)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcategorias', to='core_api.categoria')),
            ],
            options={
                'db_table': 'subcategoria',
            },
        ),
        migrations.AddField(
            model_name='documento',
            name='subcategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='core_api.subcategoria'),
        ),
        migrations.AddField(
            model_name='documento',
            name='tipo_documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='core_api.tipodocumento'),
        ),
        migrations.AddConstraint(
            model_name='categoria',
            constraint=models.UniqueConstraint(fields=('area', 'nome'), name='uq_categoria_area_nome'),
        ),
        migrations.AddConstraint(
            model_name='chunk',
            constraint=models.UniqueConstraint(fields=('documento', 'ordem'), name='uq_chunk_documento_ordem'),
        ),
        migrations.AddConstraint(
            model_name='documentoarea',
            constraint=models.UniqueConstraint(fields=('documento', 'area'), name='uq_documento_area'),
        ),
        migrations.AddConstraint(
            model_name='documentoarea',
            constraint=models.UniqueConstraint(condition=models.Q(('is_principal', True)), fields=('documento',), name='uq_documento_area_principal'),
        ),
        migrations.AddIndex(
            model_name='embeddingversion',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='embedding_version_hnsw_idx', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddConstraint(
            model_name='embeddingversion',
            constraint=models.UniqueConstraint(condition=models.Q(('vigente', True)), fields=('chunk',), name='uq_embedding_version_vigente_por_chunk'),
        ),
        migrations.AddIndex(
            model_name='logacesso',
            index=models.Index(fields=['documento', 'criado_em'], name='log_acesso_documen_9fb7e6_idx'),
        ),
        migrations.AddConstraint(
            model_name='subcategoria',
            constraint=models.UniqueConstraint(fields=('categoria', 'nome'), name='uq_subcategoria_categoria_nome'),
        ),
        migrations.AddConstraint(
            model_name='documento',
            constraint=models.UniqueConstraint(fields=('identificador_codigo', 'numero_revisao'), name='uq_documento_identificador_revisao'),
        ),
        migrations.AddConstraint(
            model_name='documento',
            constraint=models.CheckConstraint(condition=models.Q(('titulo', ''), _negated=True), name='ck_documento_titulo_nao_vazio'),
        ),
        migrations.AddConstraint(
            model_name='documento',
            constraint=models.CheckConstraint(condition=models.Q(('identificador_codigo', ''), _negated=True), name='ck_documento_identificador_nao_vazio'),
        ),
        migrations.AddConstraint(
            model_name='documento',
            constraint=models.CheckConstraint(condition=models.Q(('numero_revisao', ''), _negated=True), name='ck_documento_numero_revisao_nao_vazio'),
        ),
        migrations.AddConstraint(
            model_name='documento',
            constraint=models.CheckConstraint(condition=models.Q(('origem_fonte', ''), _negated=True), name='ck_documento_origem_nao_vazia'),
        ),
        migrations.AddConstraint(
            model_name='documento',
            constraint=models.CheckConstraint(condition=models.Q(('arquivo_original_url', ''), _negated=True), name='ck_documento_arquivo_nao_vazio'),
        ),
    ]
