# Generated by Django 5.2.7 on 2026-09-24 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core_api", "0003_area_principal_trigger"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistroPergunta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("usuario_id", models.UUIDField(blank=True, null=True)),
                ("pergunta", models.TextField()),
                ("encontrou", models.BooleanField()),
                ("quantidade_fontes", models.PositiveSmallIntegerField(default=0)),
                ("tempo_busca_ms", models.PositiveIntegerField()),
                ("tempo_ia_ms", models.PositiveIntegerField()),
                ("tempo_total_ms", models.PositiveIntegerField()),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Registro de Pergunta",
                "verbose_name_plural": "Registros de Perguntas",
                "db_table": "registro_pergunta",
                "ordering": ["-criado_em"],
            },
        ),
    ]
