# Generated by Django 5.2.7 on 2026-09-22 00:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Papel',
            fields=[
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'verbose_name': 'Papel',
                'verbose_name_plural': 'Papéis',
                'db_table': 'papel',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=180, unique=True)),
                ('senha_hash', models.CharField(max_length=255)),
                ('ultimo_login_em', models.DateTimeField(blank=True, null=True)),
                ('tentativas_login_falhas', models.IntegerField(db_column='tentativas_login_f', default=0)),
                ('bloqueado_ate', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('papel', models.ForeignKey(db_column='papel', on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='credenciais.papel')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'usuario',
            },
        ),
    ]
